### ISSUE TITLE
Profiles not recognized with Build123 on Windows.

### ISSUE THREAD

**Issue by borisbrodski** [cosminadrianpopescu/vim-sql-workbench#27] opened 2018-02-06 14:20 UTC
Following the tutorial I'm stack with the step connecting the buffer to a profile. CtrlP extension shows no Profiles.

g:sw_config_dir is set, there are some profiles in the WbProfiles.xml.

**Comment by cosminadrianpopescu** [comment] 2018-02-06 14:22
you also have to set the g:sw_tmp (if you are on windows) and g:sw_exe variables.

**Comment by cosminadrianpopescu** [comment] 2018-02-06 14:22
From tutorial: 

set the g:sw_config_dir, g:sw_exe and g:sw_cache variables
for cygwin environments, please also set the g:sw_plugin_path variable (this should point to the installation directory of the plugin). For example: c:/Users/cosmin/.vim/bundle/vim-sql-workbench

**Comment by borisbrodski** [comment] 2018-02-07 10:10
Here is my configuration:

```
let g:sw_config_dir='C:\Users\me\.sqlworkbench\'
let g:sw_exe='c:\Users\me\Software\sql-workbench-build123\sqlwbconsole.cmd'
let g:sw_tmp='c:\tmp'
let g:sw_cache='C:\Users\me\.cache\sql-workbench'
if !exists("g:ctrlp_extensions")
  let g:ctrlp_extensions=[]
endif
call add(g:ctrlp_extensions, "sw_profiles")
```

Notes:
* If I run c:\Users\me\Software\sql-workbench-build123\sqlwbconsole.cmd from CMD I get
```
SQL Workbench/J (123) console interface started.
Enter exit to quit.
Enter WbHelp for a list of SQL Workbench/J specific commands
Config directory: C:\Users\me\.sqlworkbench
```

* Directory `C:\Users\me\.cache\sql-workbench` exists and is empty
* Directory `C:\Users\me\.sqlworkbench\` exists and contains following files:
```
Default.wksp
Default.wksp.1
WbDrivers.xml
WbProfiles.xml
WbProfiles.xml.1
WbProfiles.xml.2
WbProfiles.xml.3
WbProfiles.xml.4
WbProfiles.xml.5
workbench.log
workbench.settings
workbench.settings.1
```
* In SQL-Workbench GUI I have 3 profiles

Vim starts without any errors. When I press Ctrl+P and Ctrl+B to see the profiles, there is just nothing to select.

**Comment by cosminadrianpopescu** [comment] 2018-02-07 12:00
You need to create the folder `c:\Users\me\.cache\sql-workbench\sw`. It's a bug in the tutorial and the working of the plugin. I will fix it with the next version. 

Please let me know if it's ok after creating the `sw` folder (it should be ok).

**Comment by borisbrodski** [comment] 2018-02-08 09:51
Unfortunately this doesn't helped.

Debugging the source code I found out, that the  sqlwbconsole.cmd executes and `wbabout;` and `exit` commands are send. (But surprisingly no `WbListProfiles;`)
But the output of the command `wbabout` never arrives. The hander of the call `sw#profiles#about` never gets called. The last message, that comes from the sqlwbconsole.cmd are the 4 greeting lines:

```
SQL Workbench/J (123) console interface started.
Enter exit to quit.
Enter WbHelp for a list of SQL Workbench/J specific commands
Config directory: C:\Users\me\.sqlworkbench
```

So for me it looks, like the plugin doesn't wait for the output sending more and more commands and then closing the process without waiting for the output to arrive.

**Comment by cosminadrianpopescu** [comment] 2018-02-09 08:32
Could you try to set it not to use `jline`? In the config file (`C:\Users\me\.sqlworkbench\workbench.settings`), add this line:

```
workbench.console.use.jline=false
```

I think this will fix it. It looks (from the description of the debug that you've put there) that the vim job cannot read the output. And this could happen because of this.

**Comment by borisbrodski** [comment] 2018-02-09 12:36
This worked! Thank you very much.

One bug I also have found is, that the profiles with a space in the name doesn't work at all. Are you aware of this?

**Comment by cosminadrianpopescu** [comment] 2018-02-09 12:37
No. I will fix both issues with a next release. Thank you for finding them (the bugs)

**Comment by borisbrodski** [comment] 2018-02-09 12:57
Also the name of the profile, username and maybe also the password can't contains spaces nor other special characters, like _ - . / ...

If they do, the following message appears:

```
=SQL 1
A profile name or connection information is required.
Parameters for WbConnect are:
-profile        The name of the connection profile to connect to 
or
-username              The DB user for the connection
-password              The password for the DB user
-url                   The JDBC URL to connect to
-driver                The driver class to use
-driverJar             The classpath for the driver
-autocommit            Control the autocommit setting
-rollbackOnDisconnect  Issue a rollback before the connection is closed
-emptyStringIsNull     Treat empty strings as null
-trimCharData          Trim values from CHAR columns
Execution time: 0s
```

**Comment by cosminadrianpopescu** [comment] 2018-02-09 13:03
If you tried to connect via the `CtrlP` plugin, this should only do `wbconnect -profile=... -group=...`. So the user can contain anything. If there is an issue there, then the issue is with `SQL Workbench/J`, not with the plugin. However, the space in the group or the profile is an issue and you are right. Probably not possible to connect if you have a space in the profile name. 

If you tried directly a `wbconnect`, then it's up to you to quote the name of the user or the password. If you tried to do `SWSqlBufferConnect`, this will not execute a `wbconnect` unless you have an auto command, so it's again up to you to quote the name of the user or the password.

Hope it's clear enough. If not, let me know. I will try to explain better.

**Comment by borisbrodski** [comment] 2018-02-09 13:10
Yes, thank you! This is correct. The problem was, that the new created profiles were unknown for the running VIM.

I could reload updated profiles for CtrlP using `call sw#profiles#update('')` (F5 doesn't work)
but I couldn't connect to them. I think I have to restart the underlying `sqlwbconsole.cmd` process somehow.

It would be really great, if CtrlP's F5 could do all this ;)

**Comment by cosminadrianpopescu** [comment] 2018-02-09 13:14
You are right. If you modify the profiles you need to restart the underlying `SQL Workbench/J` connection. You can just do `SWSqlBufferDisconnect` which will kill the connection to `SQL Workbench/J`. Then, in order for `CtrlP` plugin to pick up the new profile, you need to do `call sw#profiles#update('')`. Because the profiles are fetch from the `WbProfiles.xml` file and this need to be parsed again.

**Comment by borisbrodski** [comment] 2018-02-12 12:41
Thank you for the help! Now I'm starting to actually use the plugin instead of dbext.

I think I found a couple more bugs, like

* wrong captions in the table description output
* SWSqlReferencedBy fails on the first call (a subsequent call with the same INDEX seams to work)

I will eventually find bugs in the future.

Also I already have some feature requests, like

* `:CtrlPSW` to start CtrlP in profile selection mode
* `<F5>` in CtrlP should restart everything as described above
* A new command/hotkey silently follow a foreign key if the cursor is placed on an ID, like 12345. 

So here are my questions:

* Are you interested in fixing all the bugs?
* Should I post each bug separately?
* Should I also try to fix a simple ones myself and create a pull request?
* What about feature requests?


Thank you!

**Comment by cosminadrianpopescu** [comment] 2018-02-12 13:51
> Are you interested in fixing all the bugs?

Of course. I also use the plugin in my day to day work, so I am always fixing all the bugs. 

> Should I post each bug separately?

I think it would be better, because the chance of missing something will be smaller.

> Should I also try to fix a simple ones myself and create a pull request?

Pull request are always welcome. So please try and fix any issue you can and I will include it with next releases. Only thing is, if you also open tickets for something that you work on, let me know in the ticket, so I won't be working on the same thing.

> What about feature requests?

The more the better. Sometimes I lack ideas on how to improve the plugin. 

> :CtrlPSW to start CtrlP in profile selection mode

You can already include this in your `vimrc`:  `:call ctrlp#init(ctrlp#sw_profiles#id())`. This means, that you can create the command like this:

```
command! CtrlPSW call ctrlp#init(ctrlp#sw_profiles#id())
```

I will include it anyway in a future release, but until then you can add the given line in your `vimrc`. 

> `<F5>` in CtrlP should restart everything as described above

Please open a ticket and I will work on it fo ra next release.

> A new command/hotkey silently follow a foreign key if the cursor is placed on an ID, like 12345.

Same thing. Open a ticket and I will work on it.

> wrong captions in the table description output

Could you please be more explicit? 

> SWSqlReferencedBy fails on the first call (a subsequent call with the same INDEX seams to work)

Could you provide some logs and an error more explicit? I don't understand exactly what you are saying.

**Comment by cosminadrianpopescu** [comment] 2018-03-21 20:42
With the new version that I've just published, you can now have spaces in profile names. 

There is also the possibility to clear the cache of the profiles without restarting vim. There is the command `CtrlPClearSWCache`. Please note that it is not possible (at leas to my knowledge) to bind that function for the `<F5>` in `CtrlP`. Looking in the `CtrlP` code, the `<F5>` shortcut only works for buffers or MRU. So, you can bind `F5` globally in VIM to clear the `SW` profiles cache, but then you would lose the functionality in `CtrlP`. Hope I was clear enough.

There is also the command `CtrlPSW` which will open the `CtrlP` in the `SW` tab.

I've also fixed the documentation regarding `JLine` 

So I will close this ticket.

**Closed as completed by cosminadrianpopescu** 2018-03-21 20:42 UTC

**Comment by cosminadrianpopescu** [comment] 2018-03-21 20:43
Regarding these 2 requests:

* wrong captions in the table description output
* SWSqlReferencedBy fails on the first call (a subsequent call with the same INDEX seams to work

could you please open new tickets with a more details description, as they are not clear to me.

Thank you.

**Comment by cosminadrianpopescu** [comment] 2018-03-21 20:47
Also, could you please confirm that in the new version (8.1), the <C-Space> should work?

**Comment by borisbrodski** [comment] 2018-03-22 10:13
> wrong captions in the table description output

Already created one here: https://github.com/cosminadrianpopescu/vim-sql-workbench/issues/29

> SWSqlReferencedBy fails on the first call (a subsequent call with the same INDEX seams to work
I can't reproduce it now. If it comes back, I will create the issue.

**Comment by borisbrodski** [comment] 2018-03-22 10:34
CtrlP stuff works great! Thank you!
