### ISSUE TITLE
Cannot start SWServer

### ISSUE THREAD

**Issue by CaptainQuirk** [cosminadrianpopescu/vim-sql-workbench#12] opened 2015-09-17 10:05 UTC
Hi there !

When launching

```
SWServerStart 5000
```

I get this

```
/var/folders/zx/twqljpmd34lc0pz6r8hr84380000gp/T/v2VODbO/22:90: no such file or directory: /Users/bambi/.vim/bundle/vim-sql-workbench/autoload/sw/../../resources/sqlwbconsole
```

I think this comes from line **31** in autoload/sw/server.vim.

I don't understand how this could work since there is no sqlwbconsole file in the resources folder.

I tried to symlink the console file from my SQL Workbench install directly in the resource folder, but then I get

```
Unknown parameter(s): -t /tmp -s -c /Users/bambi/home/bin/sqlwbconsole.sh -v vim -o 5000
SQL Workbench/J (118) console interface started.
Enter exit to quit.
Enter WbHelp for a list of SQL Workbench/J specific commands
Config directory: /Users/bambi/.sqlworkbench

Unknown parameter(s): -t /tmp -s -c /Users/bambi/home/bin/sqlwbconsole.sh -v vim -o 5000

SQL>
```

Thanks for your efforts, I hope it will work !

**Comment by cosminadrianpopescu** [comment] 2015-09-17 10:41
At the moment `SWServerStart` is broken. Until it gets fixed, try to start the server from terminal: 

```
cd <path-to-vim-sql-workbench-plugin>/vim-sql-workbench/resources
./sqlwbserver -c <path-to-your-sqlwbconsole.sh> -o 5000
```

This should be enough. I will fix also the `SWServerStart`. The problem with it is that it also has to work on `Windows` and I don't have any `Windows` machines available to test.

**Comment by CaptainQuirk** [comment] 2015-09-17 10:53
Can't you use one of [modernie's](https://dev.modern.ie/) virtual machines for that ?

**Comment by CaptainQuirk** [comment] 2015-09-17 11:51
So far I did
- Launch the server manually

```
/sqlwbserver -c ~/bin/sqlwbconsole.sh -o 5000
```
- Launch vim in server mode with

```
vim --servername test
```
- Create a buffer and connect it to the server

```
:SWSqlConnectToServer 5000
```
- I then tried to launch the explorer from this file (and another non sql file)

```
SWDbExplorer 5000 <db>
```
- And I got

```
Error detected while processing function sw#dbexplorer#show_panel..sw#server#open_dbexplorer..<SNR>175_pipe_execute:
line   10:
E605: Exception not caught: There is no port set for this buffer.
```

**Comment by cosminadrianpopescu** [comment] 2015-09-17 11:54
> `SWDbExplorer 5000 <db>`

It actually the other way around. Maybe a clearer error would be nice... I know. So, it's: 

`SWDbExplorer <db> 5000`

Please let me know if you still have problems.

**Comment by CaptainQuirk** [comment] 2015-09-17 12:45
Doc needs updating then ! In the **Database Explorer** section, I read

```
:SWDbExplorer 5000 myProfile
```

I launched the command and got

```
Error detected while processing function sw#dbexplorer#show_panel:
line   43:
E121: Undefined variable: b:first_tab
E116: Invalid arguments for function <SNR>178_change_tab
```

After that, I get the expected layout with 3 windows split but they are empty.

The <db> is actually a profile in the SQL Workbench sense, right ? Cos' I created it with the gui as you said.

My MySQL Database is not on localhost, but it shouldn't be a problem, right ?

**Comment by cosminadrianpopescu** [comment] 2015-09-17 12:48
Can you attach a copy of your `profiles.xml` file in the `~/.sqlworkbench` folder? Please check it before for passwords and take them out if they are there (I don't think they are, but just to be sure). Also, remove any other sensitive information that might be there (like users or so on). I am interested in the database type.

**Comment by CaptainQuirk** [comment] 2015-09-17 13:04
There you are ! By the way, the file is called WbProfiles ! Could it be related ?

```
<?xml version="1.0" encoding="UTF-8"?>
<java version="1.8.0_60" class="java.beans.XMLDecoder">
 <object class="java.util.ArrayList">
  <void method="add">
   <object class="workbench.db.ConnectionProfile">
    <void property="driverName">
     <string>MySQL</string>
    </void>
    <void property="driverclass">
     <string>com.mysql.jdbc.Driver</string>
    </void>
    <void property="name">
     <string>db</string>
    </void>
    <void property="password">
     <string>xxxx</string>
    </void>
    <void property="storeExplorerSchema">
     <boolean>true</boolean>
    </void>
    <void property="url">
     <string>jdbc:mysql://192.168.2.63:3306/db</string>
    </void>
    <void property="useSeparateConnectionPerTab">
     <boolean>true</boolean>
    </void>
    <void property="username">
     <string>xxxx</string>
    </void>
   </object>
  </void>
 </object>
</java>
```

I have access to my database in SQL Workbench itself.

**Comment by cosminadrianpopescu** [comment] 2015-09-17 13:07
The name of the profile it seems to be db, not myProfile. You did `SWDbExplorer db 5000`, right? Could you please confirm?

Thank you, 
Cosmin Popescu.

**Comment by CaptainQuirk** [comment] 2015-09-17 13:14
Db is not the actual name, I hid it for the same reason I hid username and password. (myProfile comes from the readme).
The value I'm using in vim matches the value in the original xml profile file.

**Comment by cosminadrianpopescu** [comment] 2015-09-17 13:37
I am asking because the error means that the database profile is not found and the plugin cannot open any tabs for the current profile. Check the following: 
- You have the password saved in the sql workbench profile (otherwise sql workbench will ask it interactively and will block). I plan to add a feature to interact with the `SQL Workbench/J` in the console mode, but for now is like this. 
- You created the profile before starting the `sqlwbserver`. If no, `sqlwbserver` needs a restart. `ctrl+c` in the terminal window where is opened and open it again.

**Comment by CaptainQuirk** [comment] 2015-09-17 13:47
As I said, I can connect to my database with SQL Workbench (password is in the profile). I restarted the server but I still get the same error

**Comment by cosminadrianpopescu** [comment] 2015-09-17 14:13
And you are not putting anything like quotes or something else around the name, of the profile, I suppose. Could you please check the `g:SW_Tabs` variable? Could you please in vim do in command mode: `let @a = string(g:SW_Tabs)`

Then in a buffer, in normal mode do `"ap` and then get the content of the buffer and attach it here. 

Thank you, 
Cosmin Popescu

**Comment by CaptainQuirk** [comment] 2015-09-17 14:50
There you are !

{':oracle': [{'panels': [{'shortcut': 'H', 'title': 'Show the host', 'command': 'select host from user_db_links where db_link = ''%object%'''}], 'shortcut': 'L', 'title': 'DB Links', 'command': 'select db_link, username, created  from user_db_links;'}, {'panels': [{'shortcut': 'S', 'hide_header': 1, 'filetype': 'sql', 'title': 'Job source', 'command': 'select job_action from user_scheduler_jobs where job_name = ''%object%'''}], 'shortcut': 'J', 'title': 'User Jobs', 'command': 'select job_name, job_creator, start_date, repeat_interval from user_scheduler_jobs'}, {'panels': [{'shortcut': 'S', 'filetype': 'sql', 'title': 'SQL Source', 'command': 'wbprocsource %object%'}, {'shortcut': 'E', 'title': 'Compile', 'command': 'alter package %object% compile package'}], 'shortcut': 'K', 'title': 'Packages', 'command': 'select OBJECT_NAME, OBJECT_TYPE, STATUS from user_objects where object_type in (''PACKAGE'');'}, {'panels': [{'shortcut': 'H', 'title': 'Select schema', 'command': 'alter session set current_schema = %object%;'}], 'shortcut': 'M', 'title': 'Show schemas', 'command': 'wblistschemas;'}], ':postgresql': [{'panels': [{'shortcut': 'C', 'title': 'Columns', 'command': 'desc %3%.%0%'}, {'shortcut': 'S', 'filetype': 'sql', 'title': 'SQL Source', 'command': 'WbGenerateScript -objects="%object%"'}, {'shortcut': 'D', 'title': 'Data', 'command': 'select \* from %3%.%0%'}, {'shortcut': 'I', 'title': 'Indexes', 'command': 'WbListIndexes -tableName=%object% -schema=%3%'}, {'shortcut': 'R', 'skip_columns': [2], 'title': 'Referenced by', 'command': 'WbGrepSource -searchValues="references %object%" -types=TABLE -useRegex=false -schemas=_;'}], 'shortcut': 'O', 'title': 'Objects', 'command': 'WbList'}, {'panels': [{'shortcut': 'S', 'filetype': 'sql', 'title': 'SQL Source', 'command': ':sw#dbexplorer#postgre_proc'}], 'shortcut': 'P', 'title': 'Procedures', 'command': 'WbListProcs;'}, {'panels': [{'shortcut': 'S', 'hide_header': 1, 'skip_columns': [0, 1], 'filetype': 'sql', 'title': 'SQL Source', 'command': 'WbGrepSource -searchValues="%object%" -objects=%object% -types=_ -useRegex=true -schemas=_; -- AFTERcall sw#dbexplorer#fix_source_code()'}], 'shortcut': 'T', 'title': 'Triggers', 'command': 'WbListTriggers;'}, {'panels': [{'shortcut': 'H', 'title': 'Select schema', 'command': 'set search_path to %object%;'}, {'shortcut': 'A', 'title': 'Select *', 'command': 'set search_path to ''_._'''}], 'shortcut': 'M', 'title': 'Show schemas', 'command': 'wblistschemas;'}, {'panels': [], 'shortcut': 'W', 'title': 'Row Counts', 'command': 'WbRowCount;'}], '^postgresql': [{'panels': [{'shortcut': 'C', 'title': 'Columns', 'command': 'desc %object%;'}, {'shortcut': 'S', 'filetype': 'sql', 'title': 'SQL Source', 'command': 'WbGenerateScript -objects="%object%"'}, {'shortcut': 'D', 'title': 'Data', 'command': 'select \* from %object%;'}, {'shortcut': 'I', 'title': 'Indexes', 'command': 'WbListIndexes -tableName=%object%;'}, {'shortcut': 'R', 'skip_columns': [2], 'title': 'Referenced by', 'command': 'WbGrepSource -searchValues="references %object%" -types=TABLE -useRegex=false;'}], 'shortcut': 'O', 'title': 'Objects', 'command': 'WbList -objects=% -types=SYNONYM,SEQUENCE,TABLE,TYPE,VIEW'}, {'panels': [{'shortcut': 'S', 'filetype': 'sql', 'title': 'SQL Source', 'command': 'WbProcSource %object%'}], 'shortcut': 'P', 'title': 'Procedures', 'command': 'WbListProcs;'}, {'panels': [{'shortcut': 'S', 'filetype': 'sql', 'skip_columns': [0, 1], 'hide_header': 1, 'title': 'SQL Source', 'command': 'WbGrepSource -searchValues="%object%" -objects=%object% -types=_ -useRegex=true; -- AFTERcall sw#dbexplorer#fix_source_code()'}], 'shortcut': 'T', 'title': 'Triggers', 'command': 'WbListTriggers;'}, {'panels': [], 'shortcut': 'W', 'title': 'Row Counts', 'command': 'WbRowCount;'}]}

**Comment by cosminadrianpopescu** [comment] 2015-09-17 14:56
![dbexplorer](https://cloud.githubusercontent.com/assets/5187873/9936634/342423b0-5d5d-11e5-8774-462082b06efa.png)

It really looks strange. Could you please do following: 
- download attached `dbexplorer.png` and rename it to `dbexplorer.vim`
- copy it in your `<path-to-vim-sql-workbench>/autoload/sw` (overwrite the existing one)
- close and reopen vim
- do again `SWDbExplorer db 5000` (now you should have the empty windows but without error)
- then click `<shift+o>`. 

Let me know how this works. 

Thank you, 
Cosmin Popescu.

**Comment by CaptainQuirk** [comment] 2015-09-17 15:11
What you've attached looks like a png

**Comment by cosminadrianpopescu** [comment] 2015-09-17 15:12
Yes, rename it as `dbexplorer.vim` (I can only attache images apparently to the ticket).

**Comment by CaptainQuirk** [comment] 2015-09-17 15:31
**Click** `<shift+o>` ?

**Comment by cosminadrianpopescu** [comment] 2015-09-17 15:33
Press `<shift+o>`. Sorry.

**Comment by CaptainQuirk** [comment] 2015-09-17 15:39
```
Cannot make changes, 'modifiable' is off
```

But I don't know if it's really related.

Otherwise, nothing

**Comment by cosminadrianpopescu** [comment] 2015-09-17 15:43
I think you have a problem with your installation of the plugin. What method are you using to install it (`pathogen` or something else)?

**Comment by CaptainQuirk** [comment] 2015-09-17 15:43
pathogen

**Comment by CaptainQuirk** [comment] 2015-09-17 16:00
<shift+o> is supposed to create a new line but it is redefined for the explorer ?

**Comment by cosminadrianpopescu** [comment] 2015-09-18 06:01
That's the idea. Can you confirm that the `resources` folder is in the `<bundle>/vim-sql-workbench` folder?

And also can you check the `resources` folder and list the content of the folder here?

Thank you,

**Comment by CaptainQuirk** [comment] 2015-09-18 07:36
```
bundle
├── vim-sql-workbench
│   ├── LICENSE
│   ├── README.md
│   ├── autoload
│   │   ├── sw
│   │   │   ├── autocomplete.vim
│   │   │   ├── cmdline.vim
│   │   │   ├── dbexplorer.vim
│   │   │   ├── search.vim
│   │   │   ├── server.vim
│   │   │   ├── session.vim
│   │   │   ├── sqlwindow.vim
│   │   │   └── variables.vim
│   │   └── sw.vim
│   ├── doc
│   │   ├── tags
│   │   └── vim-sql-workbench.txt
│   ├── plugin
│   │   └── sw.vim
│   └── resources
│       ├── dbexplorer.vim
│       ├── screenshots
│       │   ├── s01.jpg
│       │   ├── s02.jpg
│       │   ├── s03.jpg
│       │   ├── s04.jpg
│       │   ├── s05.jpg
│       │   └── s06.jpg
│       ├── shortcuts_sql_buffer_statement.vim
│       ├── shortcuts_sql_results.vim
│       ├── sqlwbconsole -> /Users/bambi/bin/SQLWorkbench/sqlwbconsole.sh
│       ├── sqlwbserver
│       ├── wbprocedures2vim.xslt
│       └── wbreport2vim.xslt
```

**Comment by cosminadrianpopescu** [comment] 2015-09-18 07:44
Can you try to start the `sqlwbserver` as `./sqlwbserver -c /Users/bambi/bin/SQLWorkbench/sqlwbconsole.sh -o 5000 -d 1` and then try again to connect at the server using `SWDbExplorer db 5000` and let me know what is the output in the `sqlwbserver` terminal window?

**Comment by CaptainQuirk** [comment] 2015-09-18 09:02
In the sqlserver term window

```
Connected with 127.0.0.1:61167
OPENING DBE CONNECTION: /Users/bambi/bin/sqlwbconsole.sh -feedback=true -showProgress=false -profile=db
```

In vim I get

```
There is already a dbexplorer for db
```

**Comment by cosminadrianpopescu** [comment] 2015-09-18 09:45
Restart also vim, please.

**Comment by CaptainQuirk** [comment] 2015-09-18 10:07
Done.

Still the same message. That's not something I had yesterday

**Comment by cosminadrianpopescu** [comment] 2015-09-18 10:34
Do you have something saving the sessions? Making `mksession`? Because that is the only explanation. `There is already a dbexplorer for db` means that you have another database explorer opened in the same vim instance. But since you just opened the `vim` again there is no way you could possibly get this message, unless you have a `mksession` before and `so` afterwards. Could you please check?

**Comment by CaptainQuirk** [comment] 2015-09-18 10:41
Good guess. I use vim-obsession !

Now, I have the three buffers again. But they are empty !

In the console, I get this:

```
Connected with 127.0.0.1:58823
```

**Comment by cosminadrianpopescu** [comment] 2015-09-18 10:47
Ok, now  press `<shift+o>`

**Comment by CaptainQuirk** [comment] 2015-09-18 10:50
Still the same message

```
Cannot make changes, 'modifiable' is off
```

Same message I get in the NERDTree panel by the way

**Comment by cosminadrianpopescu** [comment] 2015-09-18 10:55
Could you please do (after the `SWDbExplorer` and `nmap <buffer>` and attach the output here and then a `messages` and attach the output here)?

**Comment by cosminadrianpopescu** [comment] 2015-09-18 10:56
Also, do you have a plugin doing `mkview` and then have this view restored? If so, please delete the file that it has been created for this buffer.

**Comment by CaptainQuirk** [comment] 2015-09-18 11:06
```
:nmap <buffer>
n  <Tab>        @:call sw#dbexplorer#switch_bottom_panels()<CR>
n  y<C-G>      *@:call setreg(v:register, <SNR>43_recall())<CR>
```

```
:messages

Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing command line:
E484: Can't open file Session.vim
"practice.md" 19L, 460C
"practice.md" 19L, 460C
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
search hit BOTTOM, continuing at TOP
E486: Pattern not found: simulator_ios
No mapping found
E21: Cannot make changes, 'modifiable' is off
```

No mkview call in my entire bundle directory

**Comment by cosminadrianpopescu** [comment] 2015-09-18 11:23
Can you try and replace the `dbexplorer.vim` again with the one attached (rename it from `png`) and then close and restart `vim` and `sqlwbserver` and then do again `SWDbExplorer db 5000` and then do `call sw#dbexplorer#change_tab("WbList -objects=% -types=SYNONYM,SEQUENCE,TABLE,TYPE,VIEW", "O", "Objects")` and let me know if this works? 

Don't forget to not load any session. 

I am trying to determine the root cause of the problem. 

![dbexplorer](https://cloud.githubusercontent.com/assets/5187873/9958256/6f685882-5e08-11e5-9879-2de3e9c04f61.png)

**Comment by CaptainQuirk** [comment] 2015-09-18 11:52
In the sqlwbserver window I get

```
Connection to "User=root, Database=db, URL=jdbc:mysql://192.168.2.63:3306/db" successful

root@db> set maxrows = 100;

maxrows set to 100

root@db> WbList -objects=% -types=SYNONYM,SEQUENCE,TABLE,TYPE,VIEW;

---- List of database objects
NAME                        | TYPE  | DATABASE      | SCHEMA | REMARKS
----------------------------+-------+---------------+--------+--------
admins                      | TABLE | db            |        | |
articulations               | TABLE | db |          | 
cake_sessions               | TABLE | db |        |
countries                   | TABLE | db |        |
country_langs               | TABLE | db |        |
country_options             | TABLE | db |        |
exercise_tabs               | TABLE | db |        |
exercise_type_content_types | TABLE | db |        |
exercise_type_contents      | TABLE | db |        |
exercise_types              | TABLE | db |        |
exercises                   | TABLE | db |        |
i18n                        | TABLE | db |        |
langs                       | TABLE | db |        |
limbs                       | TABLE | db |        |
muscles                     | TABLE | db |        |
parameters                  | TABLE | db |        |
roles                       | TABLE | db |        |
slugs                       | TABLE | db |        |
translations                | TABLE | db |        |

(19 Rows)

root@db> wbsetconfig send_to_vim=1;

send_to_vim set to "1"
```

In the upper vim buffer, I get

```
The current profile is deb
Main shortcuts:

Available shortcuts in the right panel:: Export (E) | Open in new buffer (B)
```

Sorry for the presentation, replaced the actual db name

**Comment by cosminadrianpopescu** [comment] 2015-09-18 11:53
And in the bottom panels you should get the output, It's not the case?

**Comment by CaptainQuirk** [comment] 2015-09-18 11:54
Nope

**Comment by cosminadrianpopescu** [comment] 2015-09-18 11:54
What do you have in the bottom panels?

**Comment by CaptainQuirk** [comment] 2015-09-18 11:56
nothing.

**Comment by cosminadrianpopescu** [comment] 2015-09-18 12:01
Aaaa. Did you started vim in server mode? That is the problem. Sorry, I should've realized earlier. You need to start `vim` in server mode. Could you please confirm that this was the issue?

**Comment by CaptainQuirk** [comment] 2015-09-18 12:02
it is started in server mode.

```
vim --servername test
```

**Comment by cosminadrianpopescu** [comment] 2015-09-18 12:03
Could you check in `vim`? Do in command mode `echo v:servername`. It should display test (to be sure that is also compiled with server capabilities.

**Comment by CaptainQuirk** [comment] 2015-09-18 12:05
I recompiled vim with Homebrew with the flag --with-client-server just to try your plugin !
And yes, echo `echo v:servername` yields `TEST`

**Comment by CaptainQuirk** [comment] 2015-09-18 12:15
I have other instances of vim running in parallel in other terminals but not in server mode. Could this be an issue ?

**Comment by cosminadrianpopescu** [comment] 2015-09-18 12:16
The thing is that the command gets passed to the `sqlwbserver` instance, it is acknowledge, sent to the `SQL Workbench/J` which process it and returns the proper result, but that result is not sent to `vim` from some reason. 

The problem here is that there is nothing in the messages (no error). I will implement this evening a ping from the `sqlwbserver` to vim and see if this works in your case. And some more verbose details to try to see what is going on and let you know. Then you can update the plugin, try again and attach here the output. 

Because I cannot really think of any reason why this would not work.

**Comment by cosminadrianpopescu** [comment] 2015-09-18 12:17
> I have other instances of vim running in parallel in other terminals but not in server mode. Could this be an issue ?

No, if they are not started in server mode (and even so, it should still work). Whenever a command is sent to `sqlwbserver`, is sent together with its `servername`. so there should not be any issue with this.

**Comment by CaptainQuirk** [comment] 2015-09-18 12:20
Ok, thanks for the effort. 

I guess it must be related to my specific configuration. FWIW, you can find my vim configuration
[here](https://github.com/CaptainQuirk/.vim)

Basic configuration is split in different files in **vimrc.d** and plugin customizations are in the **plugin** directory !

**Comment by cosminadrianpopescu** [comment] 2015-09-18 19:30
Please download the plugin from here: https://popescu.eu.com/cloud/index.php/s/Kx6ZuXhtOGdpWB3

This should contain some debug infos. Then:
- restart `vim`
- `./sqlwbserver -c <path-to-your-sqlworkbench> -d 1 -l /tmp/sqlwbserver.log`
- in vim do `SWDbExplorer db 5000`
- in a new buffer in vim do `"zp`
- get the content of this buffer and of the `/tmp/sqlwbserver.log` and paste them here

Please note that `/tmp/sqlwbserver.log` can be any location on your computer

**Comment by CaptainQuirk** [comment] 2015-09-22 06:55
I'll look into it today, thanks

**Comment by CaptainQuirk** [comment] 2015-09-28 11:11
I get a non certified certificate error on you link. Can you provide a valid one please ?

**Comment by cosminadrianpopescu** [comment] 2015-09-28 14:06
Just accept the certificate. It is generated by myself on my server, so there should be no problem.

**Comment by CaptainQuirk** [comment] 2015-09-30 15:02
Hi,

Did as you asked
- There is nothing in the **z** register. `"zp` doesn't produce any output in a new buffer and checking with `:registers` confirms it
- Content of my log file

```
newConnection>>>>>>>>>>>>>>>
16
newConnection>>>>>>>>>>>>>>>
DBE
dbExplorer>>>>>>>>>>>>>>>
sqlworkbench
spawnDbeConnection>>>>>>>>>>>>>>>
OPENING DBE CONNECTION: /Users/leonard/bin/sqlwbconsole.sh -feedback=true -showProgress=false -profile=sqlworkbench
```

As a sidenote, I understood that it was a self-signed certificate ; I dont think you should provide a link pointing to a domain which certificate is self-signed on github.

**Comment by cosminadrianpopescu** [comment] 2015-09-30 15:24
> As a sidenote, I understood that it was a self-signed certificate ; I dont think you should provide a link pointing to a domain which certificate is self-signed on github. 

I totally disagree. Sign your own certificate. What will bring you a signed certificate? But this is a topic for another ticked :)

**Comment by cosminadrianpopescu** [comment] 2015-09-30 15:34
Anyways, more to the point. Are you sure you replaced the files? Because there is no way there is nothing in the `z` register. Check the `server.vim` in the plugin folder. On top of the file there is a `let @z = ''`. So at least it should be an empty register. Is it empty or not set at all?

**Comment by CaptainQuirk** [comment] 2015-10-01 14:11
The expression you mentioned is in the `server.vim` file.

The register exists but is empty

**Comment by cosminadrianpopescu** [comment] 2015-10-09 06:11
Could you please also paste the log from `sqlwbserver`?

**Comment by cosminadrianpopescu** [comment] 2015-10-09 06:17
To me it looks that there is an issue of communication between `sqlwbserver` and your `vim` instance. If I look at the `sqlwbserver` log, I see that nothing is received by `sqlwbserver`. 

You should have something like this:

```
newConnection>>>>>>>>>>>>>>>
22
newConnection>>>>>>>>>>>>>>>
DBE
dbExplorer>>>>>>>>>>>>>>>
profile
spawnDbeConnection>>>>>>>>>>>>>>>
OPENING DBE CONNECTION: sqlwbconsole.sh -feedback=true -showProgress=false -profile=profile
newConnection>>>>>>>>>>>>>>>
77
newConnection>>>>>>>>>>>>>>>
DBE
dbExplorer>>>>>>>>>>>>>>>
profile
dbExplorer>>>>>>>>>>>>>>>
select db_link, username, created  from user_db_links;;
dbExplorer#stdin.write>>>>>>>>>>>>>>>
SEND TO SERVER: select db_link, username, created  from user_db_links;;
wbsetconfig send_to_vim=1;
```

Could you please do a `telnet localhost 5000`? And see if you can connect? 

Thank you.

**Comment by CaptainQuirk** [comment] 2015-10-09 11:45
Hi, 

Thank you again for the time you're taking to solve this.

**1. Retrying to open the explorer with `SWDbExplorer db 5000` returns the following error**

```
Error detected while processing function sw#dbexplorer#show_panel:
line   43:
E121: Undefined variable: b:first_tab
E116: Invalid arguments for function <SNR>157_change_tab
```

The **z** register is still empty

**2. Regarding the _telnet_ thing, I tried the following things**

```
$ > telnet localhost 5000
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

```
$ > telnet 127.0.0.1 5000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

In the `sqlwbconsole` window, I get the following after running telnet

```
Unhandled exception in thread started by <bound method SQLWorkbench.newConnection of <__main__.SQLWorkbench object at 0x1078203d0>>
Traceback (most recent call last):
  File "./bundle/vim-sql-workbench/resources/sqlwbserver", line 305, in newConnection
    c = conn.recv(1)
socket.error: [Errno 35] Resource temporarily unavailable
```

Is it expected ?

**Comment by CaptainQuirk** [comment] 2015-10-19 14:26
Hi,

Had to upgrade my machine and took the chance to execute your instructions again. Same results. Does my last comment shed any light on what's happening ?

**Comment by cosminadrianpopescu** [comment] 2015-10-21 09:41
No, unfortunatelly not. It looks like the vim instance cannot connect to the sqlwbserver. I don't know why this is happening. It might be a firewall issue, but then again, you can do telnet without problems, so I really am a little bit lost. I don't know exactly what else to try. 

Do you think that we can arrange a vnc session somehow?

**Comment by CaptainQuirk** [comment] 2015-11-02 15:06
Could skype or any other chatting program be enough ?

**Comment by cosminadrianpopescu** [comment] 2015-11-03 07:29
I think so. If I'm not mistaken you can share your desktop using skype.

**Comment by cosminadrianpopescu** [comment] 2016-09-28 17:26
WIth the new version, the python server is not needed anymore, so I will close the issue

**Closed as completed by cosminadrianpopescu** 2016-09-28 17:26 UTC
